### ISSUE TITLE
so do you plan implement the idea of the papers

### ISSUE THREAD

**Issue by SeekPoint** [ai-guild/ncm-adv#1]
A Hierarchical Latent Variable Encoder-Decoder Model for Generating Dialogues
Topic Aware Neural Response Generation
Emotional Chatting Machine: Emotional Conversation Generation with Internal and External Memory

**Comment by suriyadeepan** [comment]
yes.. we are working on it...

**Comment by SeekPoint** [comment]
Great ，so expecting
